package at.yawk.toml.test;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.Set;
import org.jspecify.annotations.Nullable;

/**
 * Metadata and classpath byte accessors for one embedded upstream {@code toml-test} fixture.
 *
 * <p>Use byte accessors for parser inputs when exact bytes matter. Some upstream fixtures intentionally cover BOMs,
 * line endings, and invalid encodings.</p>
 *
 * <p>Instances are generated by this library and must not be constructed by users. Record components may be added in
 * minor versions as upstream test metadata evolves.</p>
 *
 * @param id upstream test id without the {@code .toml} extension, such as {@code valid/string/simple}
 * @param valid whether this case is valid TOML and has expected tagged JSON
 * @param category upstream category directory, or an empty string for root-level valid tests
 * @param tomlSpecVersions TOML spec versions whose upstream file list includes this test
 * @param tomlResourcePath package-relative classpath resource path for the TOML fixture
 * @param expectedJsonResourcePath package-relative classpath resource path for the expected tagged JSON fixture, or {@code null} for invalid tests
 */
public record TomlTestCase(
        String id,
        boolean valid,
        String category,
        Set<TomlSpecVersion> tomlSpecVersions,
        String tomlResourcePath,
        @Nullable String expectedJsonResourcePath) {
    /**
     * Returns true if this test belongs to the supplied TOML spec version.
     *
     * @param version TOML version to check
     * @return true if included in that version's upstream file list
     */
    public boolean supports(TomlSpecVersion version) {
        return tomlSpecVersions.contains(version);
    }

    /**
     * Reads the TOML fixture bytes exactly as packaged.
     *
     * @return TOML fixture bytes
     */
    public byte[] tomlBytes() {
        return readResource(tomlResourcePath);
    }

    /**
     * Reads the expected tagged JSON as UTF-8 text for valid tests.
     *
     * @return expected JSON text, or {@code null} for invalid tests
     */
    public @Nullable String expectedJson() {
        return expectedJsonResourcePath == null
                ? null
                : new String(readResource(expectedJsonResourcePath), StandardCharsets.UTF_8);
    }

    @Override
    public String toString() {
        return id;
    }

    private static byte[] readResource(String resourcePath) {
        try (InputStream stream = TomlTestCase.class.getResourceAsStream(resourcePath)) {
            if (stream == null) {
                throw new IllegalStateException("Missing classpath resource: " + resourcePath);
            }
            return stream.readAllBytes();
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to read TOML test resource", e);
        }
    }
}
